### ISSUE TITLE
How to get icon ?

### ISSUE THREAD

**Issue by 2155507151** [sachnr/awesomewm-dotfiles#8]
rt

**Comment by sachnr** [comment]
you need to install fonts patched with additional glyphs for icons. most popular one [https://www.nerdfonts.com/](https://www.nerdfonts.com/). then change this to whatever font you installed. https://github.com/sachnr/awesomewm-dotfiles/blob/ce0c3af1ba8755b211ab98388b5231449397eae7/theme/init.lua#L20

**Comment by 2155507151** [comment]
thanks
