### ISSUE TITLE
I want to use your dark theme how can I install it?

### ISSUE THREAD

**Issue by ghost** [sachnr/awesomewm-dotfiles#9]
hello your dark theme is really awesome but I dunno how to install it can you help by any chance?

**Comment by sachnr** [comment]
What are you having trouble with, gtk theme or the dotfiles?

**Comment by ghost** [comment]
@sachnr just a total beginner I just dont know how to use this dotfile at all? it would be good if there is any guide or sum

**Comment by sachnr** [comment]
copy paste everything into ~/.config/awesome
`git clone https://github.com/sachnr/awesomewm-dotfiles.git ~/.config/awesome`

**Comment by sachnr** [comment]
for gtk theme you will need this https://github.com/themix-project/oomox-gtk-theme

**Comment by ghost** [comment]
@sachnr thank you Sachin, does this dotfiles cover rofi too?

**Comment by ghost** [comment]
if I want to use ur catpuccin I will also need to use this right?
https://github.com/catppuccin/gtk

**Comment by sachnr** [comment]
i am using nix to generate the rofi dotfiles. you can have a look here if you want
https://github.com/sachnr/dotfiles/blob/main/modules/programs/rofi/default.nix
its taken from [here](https://github.com/adi1090x/rofi) with some values changed.
looks like this ![filename](https://github.com/sachnr/awesomewm-dotfiles/assets/56253564/a394167e-41cc-4357-9b4e-39f5fc55571b)

**Comment by sachnr** [comment]
> if I want to use ur catpuccin I will also need to use this right? https://github.com/catppuccin/gtk

yup and a qt theme for qt apps. Oomox Can Generate both qt and gtk theme, you just need to give it a color pallete thats why i am using that.

**Comment by ghost** [comment]
thank you! can I keep this open to if I face issues? (since i am not at home rn I cant install it, prob tomorrow)

**Comment by sachnr** [comment]
sure
